In [9]:
import pandas as pd

In [ ]:
subject_id = 1
experiment_id=1

eye_df_interp = pd.read_csv(f"exported_csv/eye_df_interp/eye_df_interp{subject_id:03}-{experiment_id:03}.csv")

,gx,gy,epoch_sec,hhmmss,validity_sum,trial,gx_interp,gy_interp,validity_interp
0,NaN,NaN,1.732521e+09,16:49:03.491,0,-1,NaN,NaN,1
1,0.476050,0.816155,1.732521e+09,16:49:03.506,2,-1,0.476050,0.816155,2
2,0.490610,0.818481,1.732521e+09,16:49:03.522,2,-1,0.490610,0.818481,2
3,0.520527,0.754540,1.732521e+09,16:49:03.538,2,-1,0.520527,0.754540,2
4,0.507679,0.780874,1.732521e+09,16:49:03.538,2,-1,0.507679,0.780874,2
...,...,...,...,...,...,...,...,...,...
49784,NaN,NaN,1.732522e+09,17:01:17.593,0,-1,NaN,NaN,0
49785,NaN,NaN,1.732522e+09,17:01:17.593,0,-1,NaN,NaN,0
49786,NaN,NaN,1.732522e+09,17:01:17.593,0,-1,NaN,NaN,0
49787,NaN,NaN,1.732522e+09,17:01:17.593,0,-1,NaN,NaN,0
49788,NaN,NaN,1.732522e+09,17:01:17.593,0,-1,NaN,NaN,0

In [11]:
# trialが0〜7のデータのみ抽出（-1は除外）
filtered_df = eye_df_interp[eye_df_interp['trial'].between(0, 7)]

# 各試行ごとの集計
summary_df = filtered_df.groupby('trial').agg(
    total_samples=('trial', 'count'),
    valid_sum_2=('validity_sum', lambda x: (x == 2).sum()),
    valid_interp_1_or_2=('validity_interp', lambda x: ((x == 1) | (x == 2)).sum())
).reset_index()

summary_df['rate_valid_sum_2'] = (summary_df['valid_sum_2'] * 100 / summary_df['total_samples']).round(2)
summary_df['rate_valid_interp_1_or_2'] = (summary_df['valid_interp_1_or_2'] * 100 / summary_df['total_samples']).round(2)

In [12]:
# 結果表示
print(summary_df)

   trial  total_samples  valid_sum_2  valid_interp_1_or_2  rate_valid_sum_2  \
0      0           2673         2030                 2058             75.94
1      1           2746         2027                 2064             73.82
2      2           2727         1917                 1937             70.30
3      3           2682         1929                 1955             71.92
4      4           2696         1959                 1991             72.66
5      5           2651         1857                 1883             70.05
6      6           2649         1853                 1858             69.95
7      7           2716         1839                 1851             67.71

   rate_valid_interp_1_or_2
0                     76.99
1                     75.16
2                     71.03
3                     72.89
4                     73.85
5                     71.03
6                     70.14
7                     68.15